spring:
  application:
    name: eventsystem
  datasource:
    url: jdbc:h2:mem:eventsys_DB
    username: dev
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-eventsystem
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # update
    show-sql: true