server:
  port: 8080

spring:
  profiles:
    active: ${APP_PROFILE:test} # perfil de teste ativo

  jpa:
    open-in-view: false

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

---
spring:
  config:
    activate:
      on-profile: test

  # Dados de conexão com o banco H2
  datasource:
    url: jdbc:h2:mem:testdb
    username: DEV
    password:

  # Configuração do cliente web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuração para mostrar o SQL no console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true