spring:
  application:
    name: uri2611

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/uri2611
    username: postgres
    password: escala79
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none # update | create | create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
